export default {
  name: 'homePage',
  title: 'Forside',
  type: 'document',
  groups: [
    { name: 'norwegian', title: 'Norsk' },
    { name: 'english', title: 'English' },
    { name: 'other', title: 'Annet' },
  ],
  fields: [
    {
      name: 'heroHeading',
      title: 'Hero-overskrift',
      type: 'string',
      group: 'norwegian',
    },
    {
      name: 'heroHeading_en',
      title: 'Hero heading (EN)',
      type: 'string',
      group: 'english',
    },
    {
      name: 'heroSubheading',
      title: 'Hero-underoverskrift',
      type: 'text',
      rows: 2,
      group: 'norwegian',
    },
    {
      name: 'heroSubheading_en',
      title: 'Hero subheading (EN)',
      type: 'text',
      rows: 2,
      group: 'english',
    },
    {
      name: 'heroImage',
      title: 'Hero-bilde',
      type: 'image',
      options: { hotspot: true },
      group: 'other',
    },
    {
      name: 'introHeading',
      title: 'Intro-overskrift',
      type: 'string',
      group: 'norwegian',
    },
    {
      name: 'introHeading_en',
      title: 'Intro heading (EN)',
      type: 'string',
      group: 'english',
    },
    {
      name: 'introText',
      title: 'Intro-tekst',
      type: 'text',
      rows: 4,
      group: 'norwegian',
    },
    {
      name: 'introText_en',
      title: 'Intro text (EN)',
      type: 'text',
      rows: 4,
      group: 'english',
    },
    {
      name: 'ctaHeading',
      title: 'CTA-overskrift',
      type: 'string',
      group: 'norwegian',
    },
    {
      name: 'ctaHeading_en',
      title: 'CTA heading (EN)',
      type: 'string',
      group: 'english',
    },
    {
      name: 'ctaText',
      title: 'CTA-tekst',
      type: 'text',
      rows: 3,
      group: 'norwegian',
    },
    {
      name: 'ctaText_en',
      title: 'CTA text (EN)',
      type: 'text',
      rows: 3,
      group: 'english',
    },
    {
      name: 'ctaButtonText',
      title: 'CTA-knapptekst',
      type: 'string',
      group: 'norwegian',
    },
    {
      name: 'ctaButtonText_en',
      title: 'CTA button text (EN)',
      type: 'string',
      group: 'english',
    },
    {
      name: 'title',
      title: 'Sidetittel',
      type: 'string',
      group: 'norwegian',
    },
    {
      name: 'title_en',
      title: 'Page title (EN)',
      type: 'string',
      group: 'english',
    },
    {
      name: 'featuredServices',
      title: 'Fremhevede tjenester',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'service' }] }],
      group: 'other',
    },
    {
      name: 'featuredClients',
      title: 'Fremhevede kunder',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'client' }] }],
      group: 'other',
    },
  ],
  preview: {
    prepare() {
      return { title: 'Forside' }
    },
  },
}
