export default {
  name: 'service',
  title: 'Tjeneste',
  type: 'document',
  groups: [
    { name: 'norwegian', title: 'Norsk' },
    { name: 'english', title: 'English' },
    { name: 'other', title: 'Annet' },
  ],
  fields: [
    {
      name: 'title',
      title: 'Tittel',
      type: 'string',
      validation: Rule => Rule.required(),
      group: 'norwegian',
    },
    {
      name: 'title_en',
      title: 'Title (EN)',
      type: 'string',
      group: 'english',
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title' },
      validation: Rule => Rule.required(),
      group: 'other',
    },
    {
      name: 'shortDescription',
      title: 'Kort beskrivelse',
      type: 'text',
      rows: 3,
      group: 'norwegian',
    },
    {
      name: 'shortDescription_en',
      title: 'Short description (EN)',
      type: 'text',
      rows: 3,
      group: 'english',
    },
    {
      name: 'fullDescription',
      title: 'Full beskrivelse',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'norwegian',
    },
    {
      name: 'fullDescription_en',
      title: 'Full description (EN)',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'english',
    },
    {
      name: 'features',
      title: 'Funksjoner',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'norwegian',
    },
    {
      name: 'features_en',
      title: 'Features (EN)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'english',
    },
    {
      name: 'icon',
      title: 'Ikon',
      type: 'string',
      group: 'other',
    },
    {
      name: 'image',
      title: 'Bilde',
      type: 'image',
      options: { hotspot: true },
      group: 'other',
    },
  ],
  preview: {
    select: { title: 'title', media: 'image' },
  },
}
